---
title: "Bottle Markdown"
date: "3/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Set WD & Load Data
setwd("D:/")
Bottle = read.csv("Bottle.csv")
Bottle1 = read.table("Bottle.csv", sep=',', header = TRUE, fill = TRUE, quote="\"")
identical(Bottle, Bottle1)
```

```{r}
setwd("D:/")
Cast = read.csv("Cast.csv")
Cast1 = read.table("Cast.csv", sep=',', header = TRUE, fill = TRUE, quote="\"")
```

```{r}
#Subset Data Based on Desired Rows & Columns for Bottle DF

Bottle2 = Bottle[c(728478:776142), c("Cst_Cnt", "Btl_Cnt", "Depthm", "LightP", "PO4uM", "NO2uM", "NO3uM", "NH3uM")]
Bottle3 = Bottle2 %>%
  filter(Cst_Cnt >= 29339,
         Cst_Cnt <= 31019
         )
```

```{r}
#Subset Data Based on Desired Rows & Columns for Cast DF Using Dplyr

library(dplyr)

Cast2 = Cast %>% 
filter(Year >= 2000,
       Year <= 2005
      )
```

```{r}
summary(Bottle3$Cst_Cnt)
summary(Cast2$Cst_Cnt)
```

```{r}
write.csv(Bottle3, "D:/Bottle_Subset.csv", row.names = FALSE)
write.csv(Cast2, "D:/Cast_Subset.csv", row.names = FALSE)
```

